title: LINDA+
description: Documentation page of the LINDA+ software.

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Carlos Pereira Atencio
repo_url: 'https://github.com/dieterich-lab/LINDAPlus'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
