title: Read The Docs Jekyll Theme
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.

# TODO: Need to figure out how to make this work
# source: docs/
# Plugin used to build from docs folder, but point to theme in root directory
#plugins:
#  - jekyll-remote-theme
#remote_theme: /srv/jekyll/

# Theme settings
site_author: Carlos Pereira Atencio
repo_url: 'https://github.com/carlosperate/jekyll-theme-rtd'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: atom-one-dark
hljs_languages: [ruby, python, javascript, bash, yaml]
