title: Read The Docs Jekyll Theme
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.
plugins: [jekyll-remote-theme]
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings docs:
# https://carlosperate.github.io/jekyll-theme-rtd/configuration/configyml.html
site_author: Carlos Pereira Atencio
repo_url: "https://github.com/carlosperate/jekyll-theme-rtd"
edit_on_github: true
github_docs_folder: true
logo: assets/img/jekyll-rtd-logo-250px.jpg
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
